### ISSUE TITLE
EADT KLN90B manual no longer online

### ISSUE THREAD

**Issue by JDeeth** [todirbg/kln90b#3]
The X-Plane.org link to the original EADT KLN90B is now dead, unfortunately. I cannot see anywhere online where the original manual / plugin is available online. (I'll have a copy on an old hard drive somewhere, though.)

Perhaps this link could substitute pending the hopeful return of the EADT manual? https://forums.x-plane.org/index.php?/files/file/18863-bendix-king-kln90b-pilots-guide/

**Comment by todirbg** [comment]
10x
EADT manual is now added in Docs folder
2093ecf
